from parameters import *
from Entities.tank import Tank
from Entities.flags import Flag
from random import randint
from Screens.tank_selection_screen import TankSelectionScreen
from Screens.game_screen import GameScreen
from Entities.engrenagem import Engrenagem
from Screens.tank_selection_screen import TankSelectionScreen
from Screens.game_screen import GameScreen
from Entities.municao import Municao