from parameters import *
from entities.tank import Tank
from entities.flags import Flag
from random import randint
from screens.tank_selection_screen import TankSelectionScreen
from screens.game_screen import GameScreen
from entities.engrenagem import Engrenagem
from screens.tank_selection_screen import TankSelectionScreen
from screens.game_screen import GameScreen
from entities.municao import Municao