from parameters import *
from entities.tank import Tank
from entities.flags import Flag
from random import randint
from Screens.tank_selection_screen import TankSelectionScreen
from Screens.game_screen import GameScreen
from entities.engrenagem import Engrenagem
from Screens.tank_selection_screen import TankSelectionScreen
from Screens.game_screen import GameScreen
from entities.municao import Municao